version: "3"
services:
  goforpomodoro:
    image: goforpomodoro
    build: .
    container_name: goforpomodorobot
    volumes:
      - ${BOT_DATA_DIR}data/go4pom_data.db:/app/data/go4pom_data.db
      - ${BOT_DATA_DIR}appsettings.toml:/app/appsettings.toml
