version: "3"
services:
  goforpomodoro:
    image: goforpomodoro
    build:
      context: .
      args:
        INTERNAL_SERVER_PORT: ${INTERNAL_SERVER_PORT}
    container_name: goforpomodorobot
    volumes:
      - ${BOT_DATA_DIR}data/go4pom_data.db:/app/data/go4pom_data.db
      - ${BOT_DATA_DIR}appsettings.toml:/app/appsettings.toml
      - ${BOT_DATA_DIR}appvariables.toml:/app/appvariables.toml
