version: "3"
services:
  goforpomodoro:
    image: goforpomodoro
    build: .
    container_name: goforpomodorobot
    volumes:
      - ${HOME}/GoforPomodoroBot/GoforPomodoroBotData/data/go4pom_data.db:/app/data/go4pom_data.db
      - ${HOME}/GoforPomodoroBot/GoforPomodoroBotData/appsettings.toml:/app/appsettings.toml
