name: GoforPomodoro
on: 
  push:
    branches:
      - 'release'
jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: production
    env:
      BOT_DATA_DIR: ${{ secrets.BOT_DATA_DIR }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build & Deploy
        run: |
          cd ${{ github.workspace }}
          docker-compose up -d --build
