name: GoforPomodoro
on: 
  push:
    branches:
      - 'release'
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Copy appvariables.toml in data folder
        run: |
          cd ${{ github.workspace }}
          cp appvariables.toml ${{ secrets.BOT_DATA_DIR }}
      - name: Build & Deploy
        run: |
          cd ${{ github.workspace }}
          BOT_DATA_DIR=${{ secrets.BOT_DATA_DIR }} INTERNAL_SERVER_PORT=${{ secrets.INTERNAL_SERVER_PORT }} docker-compose up -d --build
